# Compose file for local dev
version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: activitydb
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
